// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Vegeta REST API
This is a RESTful API for the vegeta load-testing utility. Vegeta is a versatile HTTP load testing tool built out of a need to drill HTTP services with a constant request rate.



    Schemes:
      http
      https
    Host: virtserver.swaggerhub.com
    BasePath: /api/v1
    Version: 1.0.0
    License: MIT https://opensource.org/licenses/MIT
    Contact: <nitish.malhotra@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
