// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReportByIDHandlerFunc turns a function with the right signature into a get report by ID handler
type GetReportByIDHandlerFunc func(GetReportByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReportByIDHandlerFunc) Handle(params GetReportByIDParams) middleware.Responder {
	return fn(params)
}

// GetReportByIDHandler interface for that can handle valid get report by ID params
type GetReportByIDHandler interface {
	Handle(GetReportByIDParams) middleware.Responder
}

// NewGetReportByID creates a new http.Handler for the get report by ID operation
func NewGetReportByID(ctx *middleware.Context, handler GetReportByIDHandler) *GetReportByID {
	return &GetReportByID{Context: ctx, Handler: handler}
}

/*GetReportByID swagger:route GET /report/{attackID} report getReportById

Get an attack report by  ID

*/
type GetReportByID struct {
	Context *middleware.Context
	Handler GetReportByIDHandler
}

func (o *GetReportByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReportByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
