// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Cancel cancel
// swagger:model Cancel
type Cancel struct {

	// The attack cancel object
	// Required: true
	IsCanceled *bool `json:"isCanceled"`
}

// Validate validates this cancel
func (m *Cancel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsCanceled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Cancel) validateIsCanceled(formats strfmt.Registry) error {

	if err := validate.Required("isCanceled", "body", m.IsCanceled); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Cancel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cancel) UnmarshalBinary(b []byte) error {
	var res Cancel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
