// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAttackByIDHandlerFunc turns a function with the right signature into a get attack by ID handler
type GetAttackByIDHandlerFunc func(GetAttackByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAttackByIDHandlerFunc) Handle(params GetAttackByIDParams) middleware.Responder {
	return fn(params)
}

// GetAttackByIDHandler interface for that can handle valid get attack by ID params
type GetAttackByIDHandler interface {
	Handle(GetAttackByIDParams) middleware.Responder
}

// NewGetAttackByID creates a new http.Handler for the get attack by ID operation
func NewGetAttackByID(ctx *middleware.Context, handler GetAttackByIDHandler) *GetAttackByID {
	return &GetAttackByID{Context: ctx, Handler: handler}
}

/*GetAttackByID swagger:route GET /attack/{attackID} attack getAttackById

Get attack details by ID

*/
type GetAttackByID struct {
	Context *middleware.Context
	Handler GetAttackByIDHandler
}

func (o *GetAttackByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAttackByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
