// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAttacksParams creates a new GetAttacksParams object
// no default values defined in spec.
func NewGetAttacksParams() GetAttacksParams {

	return GetAttacksParams{}
}

// GetAttacksParams contains all the bound params for the get attacks operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAttacks
type GetAttacksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAttacksParams() beforehand.
func (o *GetAttacksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
