// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "vegeta-server/models"
)

// NewPostAttackParams creates a new PostAttackParams object
// no default values defined in spec.
func NewPostAttackParams() PostAttackParams {

	return PostAttackParams{}
}

// PostAttackParams contains all the bound params for the post attack operation
// typically these are obtained from a http.Request
//
// swagger:parameters postAttack
type PostAttackParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Attack specification object. See https://github.com/tsenart/vegeta#attack-command
	  Required: true
	  In: body
	*/
	Body *models.Attack
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAttackParams() beforehand.
func (o *PostAttackParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Attack
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
