// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostAttackHandlerFunc turns a function with the right signature into a post attack handler
type PostAttackHandlerFunc func(PostAttackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAttackHandlerFunc) Handle(params PostAttackParams) middleware.Responder {
	return fn(params)
}

// PostAttackHandler interface for that can handle valid post attack params
type PostAttackHandler interface {
	Handle(PostAttackParams) middleware.Responder
}

// NewPostAttack creates a new http.Handler for the post attack operation
func NewPostAttack(ctx *middleware.Context, handler PostAttackHandler) *PostAttack {
	return &PostAttack{Context: ctx, Handler: handler}
}

/*PostAttack swagger:route POST /attack attack postAttack

Attack a target server

*/
type PostAttack struct {
	Context *middleware.Context
	Handler PostAttackHandler
}

func (o *PostAttack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostAttackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
