// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "vegeta-server/models"
)

// PutAttackByIDCancelOKCode is the HTTP code returned for type PutAttackByIDCancelOK
const PutAttackByIDCancelOKCode int = 200

/*PutAttackByIDCancelOK Success

swagger:response putAttackByIdCancelOK
*/
type PutAttackByIDCancelOK struct {

	/*
	  In: Body
	*/
	Payload *models.AttackResponse `json:"body,omitempty"`
}

// NewPutAttackByIDCancelOK creates PutAttackByIDCancelOK with default headers values
func NewPutAttackByIDCancelOK() *PutAttackByIDCancelOK {

	return &PutAttackByIDCancelOK{}
}

// WithPayload adds the payload to the put attack by Id cancel o k response
func (o *PutAttackByIDCancelOK) WithPayload(payload *models.AttackResponse) *PutAttackByIDCancelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put attack by Id cancel o k response
func (o *PutAttackByIDCancelOK) SetPayload(payload *models.AttackResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAttackByIDCancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAttackByIDCancelBadRequestCode is the HTTP code returned for type PutAttackByIDCancelBadRequest
const PutAttackByIDCancelBadRequestCode int = 400

/*PutAttackByIDCancelBadRequest Bad Request

swagger:response putAttackByIdCancelBadRequest
*/
type PutAttackByIDCancelBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAttackByIDCancelBadRequest creates PutAttackByIDCancelBadRequest with default headers values
func NewPutAttackByIDCancelBadRequest() *PutAttackByIDCancelBadRequest {

	return &PutAttackByIDCancelBadRequest{}
}

// WithPayload adds the payload to the put attack by Id cancel bad request response
func (o *PutAttackByIDCancelBadRequest) WithPayload(payload *models.Error) *PutAttackByIDCancelBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put attack by Id cancel bad request response
func (o *PutAttackByIDCancelBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAttackByIDCancelBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAttackByIDCancelNotFoundCode is the HTTP code returned for type PutAttackByIDCancelNotFound
const PutAttackByIDCancelNotFoundCode int = 404

/*PutAttackByIDCancelNotFound Not found

swagger:response putAttackByIdCancelNotFound
*/
type PutAttackByIDCancelNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAttackByIDCancelNotFound creates PutAttackByIDCancelNotFound with default headers values
func NewPutAttackByIDCancelNotFound() *PutAttackByIDCancelNotFound {

	return &PutAttackByIDCancelNotFound{}
}

// WithPayload adds the payload to the put attack by Id cancel not found response
func (o *PutAttackByIDCancelNotFound) WithPayload(payload *models.Error) *PutAttackByIDCancelNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put attack by Id cancel not found response
func (o *PutAttackByIDCancelNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAttackByIDCancelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAttackByIDCancelInternalServerErrorCode is the HTTP code returned for type PutAttackByIDCancelInternalServerError
const PutAttackByIDCancelInternalServerErrorCode int = 500

/*PutAttackByIDCancelInternalServerError Internal Server Error

swagger:response putAttackByIdCancelInternalServerError
*/
type PutAttackByIDCancelInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAttackByIDCancelInternalServerError creates PutAttackByIDCancelInternalServerError with default headers values
func NewPutAttackByIDCancelInternalServerError() *PutAttackByIDCancelInternalServerError {

	return &PutAttackByIDCancelInternalServerError{}
}

// WithPayload adds the payload to the put attack by Id cancel internal server error response
func (o *PutAttackByIDCancelInternalServerError) WithPayload(payload *models.Error) *PutAttackByIDCancelInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put attack by Id cancel internal server error response
func (o *PutAttackByIDCancelInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAttackByIDCancelInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
