// Code generated by go-swagger; DO NOT EDIT.

package attack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "vegeta-server/models"
)

// PutAttackByIDCancelOKCode is the HTTP code returned for type PutAttackByIDCancelOK
const PutAttackByIDCancelOKCode int = 200

/*PutAttackByIDCancelOK Success

swagger:response putAttackByIdCancelOK
*/
type PutAttackByIDCancelOK struct {

	/*
	  In: Body
	*/
	Payload *models.AttackResponse `json:"body,omitempty"`
}

// NewPutAttackByIDCancelOK creates PutAttackByIDCancelOK with default headers values
func NewPutAttackByIDCancelOK() *PutAttackByIDCancelOK {

	return &PutAttackByIDCancelOK{}
}

// WithPayload adds the payload to the put attack by Id cancel o k response
func (o *PutAttackByIDCancelOK) WithPayload(payload *models.AttackResponse) *PutAttackByIDCancelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put attack by Id cancel o k response
func (o *PutAttackByIDCancelOK) SetPayload(payload *models.AttackResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAttackByIDCancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAttackByIDCancelInternalServerErrorCode is the HTTP code returned for type PutAttackByIDCancelInternalServerError
const PutAttackByIDCancelInternalServerErrorCode int = 500

/*PutAttackByIDCancelInternalServerError Internal Server Error

swagger:response putAttackByIdCancelInternalServerError
*/
type PutAttackByIDCancelInternalServerError struct {
}

// NewPutAttackByIDCancelInternalServerError creates PutAttackByIDCancelInternalServerError with default headers values
func NewPutAttackByIDCancelInternalServerError() *PutAttackByIDCancelInternalServerError {

	return &PutAttackByIDCancelInternalServerError{}
}

// WriteResponse to the client
func (o *PutAttackByIDCancelInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
